// Autogenerated - do not change.

#pragma once
#include "RubyBinder.h"
#include "bondage/RuntimeHelpers.h"

namespace Debugify
{
EXPORT_DEBUGIFY const bondage::Library &bindings();
}

BONDAGE_EXPOSED_CLASS_MANAGED(EXPORT_DEBUGIFY, ::Debugify::Test)

