# Autogenerated - do not change.


require_relative '/Users/jorj/Shared/llvm/ruby-debugger/plugins/DebugifyBindings/sample/DebugifyBindings'

require_relative 'Test'

module Debugify
# number Debugify::bar(number d, number c)
# \brief 

# number Debugify::bar(number d, number c)
# Debugify::Test Debugify::foo(number a, number b)
# \brief 

end

