# Autogenerated - do not change.


require_relative '/Users/jorj/Shared/llvm/ruby-debugger/plugins/DebugifyBindings/sample/DebugifyBindings'

module Debugify

# \brief managed
#
class Test
  # nil Test::Test(number _i)
  # \brief ,

  # nil Test::Test(number _i)
  # Debugify::Test Test#boink()
  # \brief ,

  # nil Test::Test(number _i)
  # Debugify::Test Test#boink()
  # nil Test#foo(Debugify::Test t)
  # \brief 
end

end


