// Autogenerated - do not change.

#pragma once
#include "Debugger.h"
#include "Target.h"
#include "../../DebugifyBindings/EksBindings/EksBindings.h"
#include "../../DebugifyBindings/ManualBindings/ManualBindings.h"
#include "bondage/RuntimeHelpers.h"

namespace LldbDriver
{
EXPORT_DEBUGIFY const bondage::Library &bindings();
}

BONDAGE_EXPOSED_CLASS_SHARED_POINTER(EXPORT_DEBUGIFY, ::LldbDriver::Debugger)
BONDAGE_EXPOSED_CLASS_SHARED_POINTER(EXPORT_DEBUGIFY, ::LldbDriver::Target)

