# Autogenerated - do not change.


require_relative '../DebuggerBindingsInternal'

module Debugify

# \brief managed
#
class Test
  # nil Test::Test(number _i)
  # \brief ,

  # nil Test::Test(number _i)
  # Debugify::Test Test#boink()
  # \brief ,

  # nil Test::Test(number _i)
  # Debugify::Test Test#boink()
  # nil Test#foo(Debugify::Test t)
  # \brief 
end

end


