# Autogenerated - do not change.


require_relative '../BindingsInternal'

module UI

# \brief managed
#
class Application < Qt::QApplication
  # nil Application::Application(QString location)
  # \brief 
end

end


