# Autogenerated - do not change.


require_relative '../BindingsInternal'

module UI

# \brief unmanaged
#
class InputNotifier
  # number InputNotifier#listen(std::__1::function fn)
  # \brief 

  # nil InputNotifier#remove(number i)
  # \brief 
end

end


