# Autogenerated - do not change.


require_relative '../BindingsInternal'

module UI

# \brief managed
#
class MainWindow < Qt::QMainWindow
  # nil MainWindow::MainWindow()
  # nil MainWindow::MainWindow(QWidget parent)
  # \brief 

  # UI::AboutToCloseNotifier MainWindow#aboutToClose()
  # \brief 

  # UI::Console MainWindow#addConsole(QString n)
  # \brief 

  # UI::EditableTextWindow MainWindow#addEditor(QString n)
  # \brief 

  # UI::Menu MainWindow#addMenu(QString name)
  # \brief 

  # UI::Terminal MainWindow#addTerminal(QString n)
  # \brief 

  # UI::ToolBar MainWindow#addToolBar(QString n)
  # \brief 

  # UI::EditorNotifier MainWindow#editorClosed()
  # \brief 

  # UI::EditorNotifier MainWindow#editorOpened()
  # \brief 

  # QString MainWindow#geometry()
  # \brief 

  # QString MainWindow#getOpenFilename(QString caption)
  # QString MainWindow#getOpenFilename(QString caption, QString filter)
  # \brief 

  # nil MainWindow#hideDock(QWidget w)
  # \brief 

  # UI::Editor MainWindow#openFile(QString str, number line)
  # \brief 

  # UI::Editor MainWindow#openType(QString arg1)
  # \brief 

  # std::__1::shared_ptr MainWindow#process()
  # \brief 

  # boolean MainWindow#setGeometry(QString g)
  # \brief 

  # nil MainWindow#setProcess(std::__1::shared_ptr arg1)
  # \brief 

  # nil MainWindow#setTarget(std::__1::shared_ptr tar)
  # \brief 

  # nil MainWindow#showDock(QWidget w)
  # \brief 

  # std::__1::shared_ptr MainWindow#target()
  # \brief 

  # QString MainWindow::tr(string s)
  # QString MainWindow::tr(string s, string c, number n)
  # \brief 

  # QString MainWindow::trUtf8(string s)
  # QString MainWindow::trUtf8(string s, string c, number n)
  # \brief 

  # UI::TypeNotifier MainWindow#typeAdded()
  # \brief 
end

end


