# Autogenerated - do not change.


require_relative '../BindingsInternal'

module UI

# \brief managed
#
class MainWindow < Qt::QMainWindow
  # nil MainWindow::MainWindow()
  # nil MainWindow::MainWindow(QWidget parent)
  # \brief 

  # UI::Terminal MainWindow#debuggerTerminal()
  # \brief 

  # std::__1::shared_ptr MainWindow#process()
  # \brief 

  # UI::ProcessNotifier MainWindow#processChanged()
  # \brief 

  # std::__1::shared_ptr MainWindow#target()
  # \brief 

  # UI::TargetNotifier MainWindow#targetChanged()
  # \brief 

  # QString MainWindow::tr(string s)
  # QString MainWindow::tr(string s, string c, number n)
  # \brief 

  # QString MainWindow::trUtf8(string s)
  # QString MainWindow::trUtf8(string s, string c, number n)
  # \brief 
end

end


