# Autogenerated - do not change.


require_relative '../BindingsInternal'

module UI

# \brief 
#
class Terminal < Qt::QWidget
  # nil Terminal#append(QString str)
  # \brief 

  # UI::InputNotifier Terminal#input()
  # \brief 

  # QString Terminal::tr(string s)
  # QString Terminal::tr(string s, string c, number n)
  # \brief 

  # QString Terminal::trUtf8(string s)
  # QString Terminal::trUtf8(string s, string c, number n)
  # \brief 
end

end


