# Autogenerated - do not change.


require_relative '../BindingsInternal'

module UI

# \brief 
#
class Terminal < UI::Console
  # QString Terminal::tr(string s)
  # QString Terminal::tr(string s, string c, number n)
  # \brief 

  # QString Terminal::trUtf8(string s)
  # QString Terminal::trUtf8(string s, string c, number n)
  # \brief 
end

end


