# Autogenerated - do not change.


require_relative '../BindingsInternal'

require_relative 'AboutToShowNotifier'
require_relative 'MainWindow'
require_relative 'TypeNotifier'
require_relative 'AboutToCloseNotifier'
require_relative 'EditorNotifier'
require_relative 'OutputNotifier'
require_relative 'Menu'
require_relative 'ToolBar'
require_relative 'MarginClickNotifier'
require_relative 'Editor'
require_relative 'FileEditor'
require_relative 'EditableTextWindow'
require_relative 'ClickNotifier'
require_relative 'Console'
require_relative 'Terminal'
require_relative 'InputNotifier'
require_relative 'Application'

module UI


end

