# Autogenerated - do not change.


require_relative '../BindingsInternal'

module LldbDriver

# \brief sharedpointer
#
class CompileUnit
  # std::__1::shared_ptr CompileUnit#module()
  # \brief 
end

end


