# Autogenerated - do not change.


require_relative '../DebuggerBindingsInternal'

module LldbDriver

# \brief sharedpointer
#
class Debugger
  # std::__1::shared_ptr Debugger::create()
  # \brief 

  # std::__1::shared_ptr Debugger#loadTarget(Eks::StringRef str)
  # \brief Load an executable as the current target
end

end


