# Autogenerated - do not change.


require_relative '../BindingsInternal'

module LldbDriver

# \brief 
#
class FunctionMember
  # nil FunctionMember::FunctionMember()
  # nil FunctionMember::FunctionMember(LldbDriver::FunctionMember arg1)
  # \brief 

  # LldbDriver::Type FunctionMember#argument(number i)
  # \brief 

  # number FunctionMember#argumentCount()
  # \brief 

  # Eks::String FunctionMember#name()
  # \brief 

  # LldbDriver::Type FunctionMember#returnType()
  # \brief 
end

end


