# Autogenerated - do not change.


require_relative '../BindingsInternal'

module LldbDriver

# \brief sharedpointer
#
class Target
  # LldbDriver::Breakpoint Target#addBreakpoint(Eks::String file, number line)
  # \brief 

  # std::__1::shared_ptr Target#attach(number pid, LldbDriver::Error err)
  # \brief 

  # LldbDriver::Breakpoint Target#breakpointAt(number index)
  # \brief 

  # number Target#breakpointCount()
  # \brief 

  # LldbDriver::BreakpointNotifier Target#breakpointsChanged()
  # \brief 

  # std::__1::shared_ptr Target#connect(Eks::String url, LldbDriver::Error err)
  # \brief 

  # boolean, LldbDriver::Breakpoint, LldbDriver::BreakpointLocation Target#findBreakpoint(Eks::String file, number line)
  # \brief the found breakpoint
  # \param[out] 1 outBrk the found breakpoint
  # \param[out] 2 outLoc the found breakpoint location

  # std::__1::shared_ptr Target#launch(Eks::Vector args, Eks::Vector env, LldbDriver::Error err)
  # \brief 

  # std::__1::shared_ptr Target#moduleAt(number index)
  # \brief 

  # number Target#moduleCount()
  # \brief 

  # Eks::String Target#path()
  # \brief 

  # boolean Target#removeBreakpoint(LldbDriver::Breakpoint brk)
  # \brief 
end

end


