# Autogenerated - do not change.


require_relative '../DebuggerBindingsInternal'

module LldbDriver

# \brief sharedpointer
#
class Target
  # number Target#moduleCount()
  # \brief 

  # Eks::String Target#path()
  # \brief 
end

end


