# Autogenerated - do not change.


require_relative '../BindingsInternal'

module LldbDriver

# \brief 
#
class Type
  # nil Type::Type()
  # nil Type::Type(LldbDriver::Type arg1)
  # \brief 

  # LldbDriver::Type Type#canonicalType()
  # \brief 

  # std::__1::shared_ptr Type#compileUnit()
  # \brief 

  # LldbDriver::Type Type#dereferencedType()
  # \brief 

  # LldbDriver::TypeMember Type#directBaseClass(number i)
  # \brief 

  # number Type#directBaseClassCount()
  # \brief 

  # LldbDriver::FunctionMember Type#function(number i)
  # \brief 

  # number Type#functionCount()
  # \brief 

  # Eks::String Type#help()
  # \brief 

  # boolean Type#isDataStructure()
  # \brief 

  # boolean Type#isPointer()
  # \brief 

  # boolean Type#isReference()
  # \brief 

  # boolean Type#isTypedef()
  # \brief 

  # LldbDriver::TypeMember Type#member(number i)
  # \brief 

  # number Type#memberCount()
  # \brief 

  # Eks::String Type#name()
  # \brief 

  # LldbDriver::Type Type#pointeeType()
  # \brief 

  # number Type#size()
  # \brief 

  # number Type#templateArgumentCount()
  # \brief 

  # LldbDriver::Type Type#templateArgumentType(number i)
  # \brief 

  # LldbDriver::Type Type#typedefType()
  # \brief 

  # LldbDriver::TypeMember Type#virtualBaseClass(number i)
  # \brief 

  # number Type#virtualBaseClassCount()
  # \brief 
end

end


