# Autogenerated - do not change.


require_relative '../BindingsInternal'

module LldbDriver

# \brief 
#
class TypeMember
  # nil TypeMember::TypeMember()
  # nil TypeMember::TypeMember(LldbDriver::TypeMember arg1)
  # \brief 

  # number TypeMember#bitOffset()
  # \brief 

  # number TypeMember#byteOffset()
  # \brief 

  # Eks::String TypeMember#name()
  # \brief 

  # LldbDriver::Type TypeMember#type()
  # \brief 
end

end


