// Autogenerated - do not change.

#pragma once
#include "Terminal.h"
#include "MainWindow.h"
#include "FileEditor.h"
#include "Editor.h"
#include "TypeEditor.h"
#include "Application.h"
#include "../../UIBindings/QtBindings/Qt.h"
#include "../../DebugifyBindings/src/autogen/LldbDriver.h"
#include "../../BindingGenerator/EksBindings/EksBindings.h"
#include "bondage/RuntimeHelpers.h"

namespace UI
{
EXPORT_DEBUGIFY const bondage::Library &bindings();
}

BONDAGE_EXPOSED_CLASS_UNMANAGED(EXPORT_DEBUGIFY, ::UI::InputNotifier)
BONDAGE_EXPOSED_CLASS_DERIVED_MANAGED(EXPORT_DEBUGIFY, ::UI::MainWindow, ::QMainWindow, ::QWidget)
BONDAGE_EXPOSED_CLASS_UNMANAGED(EXPORT_DEBUGIFY, ::UI::ProcessNotifier)
BONDAGE_EXPOSED_CLASS_UNMANAGED(EXPORT_DEBUGIFY, ::UI::TargetNotifier)
BONDAGE_EXPOSED_CLASS_DERIVED_MANAGED(EXPORT_DEBUGIFY, ::UI::Terminal, ::QWidget, ::QWidget)
BONDAGE_EXPOSED_DERIVED_PARTIAL_CLASS(EXPORT_DEBUGIFY, ::UI::LineNumberArea, ::QWidget, ::QWidget)
BONDAGE_EXPOSED_DERIVED_PARTIAL_CLASS(EXPORT_DEBUGIFY, ::UI::Editor, ::QWidget, ::QWidget)
BONDAGE_EXPOSED_DERIVED_PARTIAL_CLASS(EXPORT_DEBUGIFY, ::UI::TypeEditor, ::UI::Editor, ::QWidget)
BONDAGE_EXPOSED_DERIVED_PARTIAL_CLASS(EXPORT_DEBUGIFY, ::UI::FileEditor, ::UI::Editor, ::QWidget)
BONDAGE_EXPOSED_CLASS_DERIVED_MANAGED(EXPORT_DEBUGIFY, ::UI::Application, ::QApplication, ::QApplication)

